### PR TITLE
Add support for types (fixes #73)

### LINKED ISSUE #73: TypeScript types
There's no types for the package available, both within the package or using `@types/snarkdown`. 😢

### PR DESCRIPTION
**Pull request by AnandChowdhary**
I've added types for people who want to use Snarkdown with TypeScript. 😄

### CODE REVIEW

**Comment by fregante** [comment]
Hope to see this merged soon

**Comment by anykeyh** [comment]
No follow up on this? :(

**Comment by kenberkeley** [comment]
Any update?

**Comment by AnandChowdhary** [comment]
This is a pretty minor update and should not affect people not using TypeScript at all, but makes the library very useful for those projects. Would love to see this merged! :)

**Comment by developit** [comment]
Apologies for the delay - I've not been doing a good job of maintaining this library since I've not had a use-case for it in a little while.

**Comment by makoven** [comment]
@developit Could you please publish a curent version (with types) to NPM

**Comment by developit** [comment]
2.0.0 has been published, apologies.

**Comment by makoven** [comment]
@developit, many thanks

**Pull request merged**
