### PR TITLE
Patches for incorrect headings parsing and fence code blocks not recognizing language class

### PR DESCRIPTION
**Pull request by Jonarod**
### Headings
Token[14] is limited to 3 `###`, while headings can range from 1 `#` to 6 `######`.
This limit leads to incorrect heading tags after 4 `####`.
This change corrects current bug : token[14] should accept between 1 to 6 `######`.

### Fence code blocks
When `language-code` is given to fence code block, we should **allow zero or more spaces** between fences and the `language` input, like this : 

````
``` [spaces] javascript
```
````

### CODE REVIEW

**Comment by developit** [comment]
@Jonarod is ~strikethrough~ part of the markdown spec, or a GFM thing?

**Comment by Jonarod** [comment]
Yeah it's not commonmark: it's more of a GFM flavoured thing. but for the cost... I thought it'd be useful :)

**Comment by developit** [comment]
Looks like 12 bytes. I might take a stab at golfing it down a bit, but I agree this is a useful addition.

**Comment by keul** [comment]
There's something unstable in that PR that prevent a merge?
I really like to have a release that fix the H1/H6 issue.

**Comment by developit** [comment]
I think switching to Microbundle made room for this!

**Pull request merged**
