### PR TITLE
WIP native trim

### PR DESCRIPTION
**Pull request by greggb**
I had started working on this before the latest refactor, so just wanted to PR it in case anything in here would be helpful to move over.

I changed the code indent regex to be 4 or more spaces to follow the spec on Daring Fireball. I also added some additional indent block tests since this ended up having a few edge cases around line breaks.

There is a difference from the original parsing with list items having a space at the end of each of them. You can see this with the combination test that I copied the example site.

Feel free to disregard and close if it's not useful, I had spent too much time on this to not push it up :).

### CODE REVIEW

**Comment by developit** [comment]
@greggb - I think we were working on spacing at the same time!  I got rid of pretty-printing whitespace entirely.

As for spacing - are you saying the Markdown spec requires 4+ spaces for indentation of things like code blocks/quotes?

**Comment by greggb** [comment]
It was a fun puzzle, but I think you're right. I had initially commented something like "I don't think native trim would work due to it trimming basically everything", but I figured I'd give it a shot.

As far as number of spaces for code blocks, yes, from what I've seen it requires either a tab or 4+ spaces to start a code block. This is a SS from Macdown:
screen shot 2017-02-26 at 6 38 32 pm

Looks like you have this repo under control. I'll keep looking out for things to contribute to!

**Comment by developit** [comment]
heh - didn't mean to put you off! switching to native trim was actually the first thing I tried after the ES2015 port landed, and I only realized I had messed up because the lovely tests @danderu added told me so! 😂

Should we close this PR then?  Your call 👍

**Comment by greggb** [comment]
Haha, not put off at all! Thanks for taking the time to explain. I enjoy using your libraries, so I'm looking forward to contributing where I can.

**Pull request closed without merging**
